@startuml


partition "Developer"  #cccccc {
  (*) --> "Add Application"
}

partition "fleet" #aaffff {
  "Add Application" --> "Create Application"
  "Create Application" --> "Create Services"
  "Create Services" --> "Increment Service Replicas"
  "Create Services" --> "Decrement Service Replicas"
  "Create Services" --> "Set Service Replicas"
  "Create Application" --> "Remove Application"
  "Remove Application" --> "Remove Services"
}

@enduml
