@startuml
|Developer|
start
|#aaffff|Application Stack|
fork
:Create Application;
:Deploy Application;
:Update Application;
:Remove Application;
fork again
:Create Service;
:Modify Service;
:Increment Service Replicas;
:Decrement Service Replicas;
:Set Service Replicas;
fork end
stop
@enduml
