@startuml


partition "Ops Manager"  #cccccc {
  (*) --> "Manage Cloud"
  (*) --> "Manage Policies"
  (*) --> "Manage Hardware"
}

partition "Cloud Stack" #aaffaa {
  "Manage Cloud" --> "Create Cloud Resources"
  "Create Cloud Resources" --> "Update Cloud Resources"
  "Update Cloud Resources" --> "Remove Cloud Resources"

  "Manage Policies" --> "Add Policy"
  "Add Policy" --> "Update Policy"
  "Update Policy" --> "Remove Policy"
}

partition "Hardware Stack" #aaffff {
  "Manage Hardware" --> "Add Hardware"
  "Add Hardware" --> "Update Hardware"
  "Update Hardware" --> "Remove Hardware"
}

@enduml
