@startuml

left to right direction

:Ops-Manager: as Actor

rectangle "fleet" #cccccc {
    (Manage Clouds) as U1
    (Manage Hardware) as U2
    (Manage Policies) as U3
}

Actor --> U1
Actor --> U2
Actor --> U3

@enduml
