@startuml
|Ops-Manager|
start
|#aaffff|fleet|
fork
:Create Cloud Resource;
:Modify Cloud Resource;
:Remove Cloud Resource;
fork again
:Create Policy;
:Modify Policy;
:Remove Policy;
fork again
:Add Hardware;
:Modify Hardware;
:Remove Hardware;
fork end
stop
@enduml
