@startuml
Actor "Ops Manager" as A

box "Manage Policies" #lightblue
participant "fleet" as S
A -> S : fleet-policy-enable
participant "Cloud Stack" as CS
S -> CS : policy/enable (name)
CS -> CS : Policy.update(name, enable)
end box
@enduml

