@startuml
|actorName|
start
|#aaffff|fleet|
:Create Compute Resource;
:Create Storage Resource;
:Create Network Resource;
:Remove Compute Resource;
:Remove Storage Resource;
:Remove Network Resource;
stop
@enduml
