@startuml
Actor "actorName" as A

box "Manage Cloud" #lightblue
participant "fleet" as S
A -> S : fleet-events-dec
participant "Cloud Stack" as CS
S -> CS : events/dec (name, amount)
CS -> CS : Events.update(name, amount)
CS -> CS : sails.helpers.handleEvents()
end box
@enduml
