@startuml
Actor "Ops Manager" as A

box "Manage-Clouds" #lightblue
participant "fleet" as S
A -> S : fleet-trigger-list
participant "Cloud Stack" as CS
S -> CS : trigger/list
CS -> CS : Trigger.find()
end box

@enduml
