@startuml
Actor "actorName" as A

box "Manage-Clouds" #lightblue
    participant "fleet" as S
    A -> S : fleet-trigger-remove(name)
    participant "Cloud Stack" as CS
    S -> CS : trigger/remove(name)
    CS -> CS : Trigger.destroy(name)
end box


@enduml
