@startuml
Actor "Ops Manager" as A

box "Manage Cloud" #lightblue
participant "fleet" as S
A -> S : fleet-events-remove
participant "Cloud Stack" as CS
S -> CS : events/remove (name)
CS -> CS : Events.destroy(name)
end box
@enduml
