@startuml
Actor "Ops Manager" as A

box "Manage Cloud" #lightblue
participant "fleet" as S
A -> S : fleet-resource-remove(name)
participant "Cloud Stack" as CS
S -> CS : resource/remove (name)
CS -> CS : Resource.destroy(name)
end box

@enduml
