@startuml
Actor "Developer" as A

box "Manage-Applications" #lightblue
participant "fleet" as S
A -> S : fleet-app-list
participant "Application Stack" as AS
S -> AS : app/list
AS -> AS : Application.find()
end box

@enduml
