@startuml
Actor "actorName" as A

box "Manage-Applications" #lightblue
participant "CLI" as S
A -> S : fleet-service-remove
participant "Application Stack" as AS
S -> AS : service/remove
AS -> AS : sails.helpers.removeApplication()
end box

@enduml
