@startuml
|Ops Manager|
start
|#aaffff|fleet|
fork
:Create Compute Hardware;
:Remove Compute Hardware;
fork again
:Create Network Hardware;
:Remove Network Hardware;
fork again
:Create Storage Hardware;
:Remove Storage Hardware;
fork end

stop
@enduml
