@startuml

package  "Application Stack" #aaffff {
  folder bin #ffffff {
    file app
    file service
    file instance
  }
  node sailsjs
  database DB1

  sailsjs .. DB1
  bin .. sailsjs
}

@enduml
