@startuml


package "Application Stack" #ccffff {
    interface CLI
    interface Web
    interface REST
    folder nodejs #ffffff {
        component sailsjs
        component sails.io
    }
    folder bin #ffffff {
      component app
      component service
      component instance
    }
}
CLI -- app
CLI -- service
CLI -- instance
app -- REST
service -- REST
instance -- REST
Web -- sailsjs
Web -- REST
REST -- sailsjs

Web -- sails.io
@enduml
