@startuml


package "Application Stack" #ccffff {
    interface CLI
    interface Web
    interface REST
    component sailsjs
    component sails.io
    component bin
}
CLI -- bin
Web -- sailsjs
REST -- sailsjs
bin - REST

Web -- sails.io
@enduml
