@startuml

partition "Application Stack" #aaffff {
  (*) --> "Create Application"
  "Create Application" --> "Create Service"
  "Create Service" --> "Create ServiceInstance"
  "Create Service" --> "Modify Service"
  "Modify Service" --> "Increment Service"
  "Modify Service" --> "Decrement Service"
  "Increment Service" --> "Create ServiceInstance"
  "Decrement Service" --> "Destroy ServiceInstance"
}

partition "Cloud Stack" #aaffaa {
    "Create ServiceInstance" --> "Create Cloud Resource"
}
@enduml
