@startuml

left to right direction

actor :Developer: as Dev

rectangle "Application Stack" #aaffaa {
UseCase UC1 as "Manage Applications"
UseCase UC2  as "Manage Services"


Dev --> UC1
Dev --> UC2
}

@enduml
