@startuml
actor Dev

Dev -> bin: app-create(name, yaml)
bin -> sailsjs : app/create(name, yaml)
Dev -> bin: app-remove
bin -> sailsjs : app/remove(name)
Dev -> bin: app-list
bin -> sailsjs : app/list
Dev -> bin: service-create
bin -> sailsjs : service/create(name)
Dev -> bin: service-dec
bin -> sailsjs : service/dec(name, amount)
Dev -> bin: service-inc
bin -> sailsjs : service/inc(name, amount)
Dev -> bin: service-list
bin -> sailsjs : service/list
Dev -> bin: service-remove
bin -> sailsjs : service/remove(name)
Dev -> bin: instance-create
bin -> sailsjs : instance/create(name)
Dev -> bin: instance-destroy
bin -> sailsjs : instance/destroy(name)
Dev -> bin: instance-list
bin -> sailsjs : instance/list

@enduml
