@startuml
actor Ops

Ops -> bin: app-create(name, yaml)
bin -> sailsjs : app/create(name, yaml)
Ops -> bin: app-remove
bin -> sailsjs : app/remove(name)
Ops -> bin: app-list
bin -> sailsjs : app/list
Ops -> bin: service-create
bin -> sailsjs : service/create(name)
Ops -> bin: service-dec
bin -> sailsjs : service/dec(name, amount)
Ops -> bin: service-inc
bin -> sailsjs : service/inc(name, amount)
Ops -> bin: service-list
bin -> sailsjs : service/list
Ops -> bin: service-remove
bin -> sailsjs : service/remove(name)
Ops -> bin: instance-create
bin -> sailsjs : instance/create(name)
Ops -> bin: instance-destroy
bin -> sailsjs : instance/destroy(name)
Ops -> bin: instance-list
bin -> sailsjs : instance/list

@enduml
