@startuml

package  "Cloud Stack" #aaffff {
  folder bin #ffffff {
    file resource
    file policy
    file trigger
    file events
  }
  node sailsjs
  database DB1

  sailsjs .. DB1
  bin .. sailsjs
}

@enduml
