@startuml

partition "Cloud Stack" #aaffff {
  (*) --> "Create Policy"
  "Create Policy" --> "Create Trigger"
  "Create Trigger" --> "Enable Policy"
  "Enable Policy" --> "Disable Policy"
  "Disable Policy" --> (*)
  (*) --> "Create Resource"
  "Create Resource" --> "Remove Resource"
  "Remove Resource" --> (*)
}

@enduml
