@startuml

left to right direction

actor :Ops Manager: as Ops

rectangle "Cloud Stack" #ccffff {
    UseCase UC1 as "Manage Clouds"
    UseCase UC2  as "Manage Policies"
}

Ops --> UC1
Ops --> UC2
@enduml
